In [48]:
#import xarray as xr
import os
import sys
import subprocess
import datetime as dt
import itertools
import numpy as np

In [56]:
mdir='/space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5'

In [77]:
fnameCanESM=lambda mdir, yyyy, mm, dd, hh, rr:f"{mdir}/cwao_CanESM5.1p1bc-v20240611_hindcast_S{yyyy:04}{mm:02}{dd:02}{hh:02}_ocean_6hr_surface_tso_r{rr:02}i00p00.nc"
fnameCanESMjoined=lambda mdir, yyyy, mm, dd, hh:f"{mdir}/joined/cwao_CanESM5.1p1bc-v20240611_hindcast_S{yyyy:04}{mm:02}{dd:02}{hh:02}_ocean_6hr_surface_tso.nc"

In [81]:
for yyyy in range(1993,2025):
    for mm in range(1,13):
        flist=[fnameCanESM(mdir,yyyy,mm,dd,hh,ii) for ii in range(1,21)]
        cmd=f"ncecat {' '.join(flist)} {fnameCanESMjoined(mdir,yyyy,mm,dd,hh)}"
        print(cmd)
        print('\n')

ncecat /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993010100_ocean_6hr_surface_tso_r01i00p00.nc /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993010100_ocean_6hr_surface_tso_r02i00p00.nc /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993010100_ocean_6hr_surface_tso_r03i00p00.nc /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993010100_ocean_6hr_surface_tso_r04i00p00.nc /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993010100_ocean_6hr_surface_tso_r05i00p00.nc /space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5/cwao_CanESM5.1p1bc-v20

In [1]:
import xarray as xr

In [5]:
test=xr.open_dataset('/space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily'
                    '/CanESM5/joined/cwao_CanESM5.1p1bc-v20240611_hindcast_S1993030100_ocean_6hr_surface_tso.nc',decode_times=False)

In [6]:
test

<xarray.Dataset> Size: 9GB
Dimensions:      (record: 20, lat: 180, bnds: 2, leadtime: 860, lon: 360)
Coordinates:
  * lat          (lat) float64 1kB -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * leadtime     (leadtime) float64 7kB 6.0 12.0 18.0 ... 5.154e+03 5.16e+03
  * lon          (lon) float64 3kB 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
    realization  |S31 31B ...
    reftime      float64 8B ...
    time         (leadtime) float64 7kB ...
Dimensions without coordinates: record, bnds
Data variables:
    hcrs         (record) |S1 20B ...
    lat_bnds     (lat, bnds) float64 3kB ...
    lon_bnds     (lon, bnds) float64 6kB ...
    tso          (record, leadtime, lat, lon) float64 9GB ...
Attributes: (12/21)
    comment:                  Produced by ECCC (Environment and Climate Chang...
    summary:                  Seasonal Forecast data produced by ECCC as its ...
    title:                    ECCC seasonal forecast model output prepared fo...
    forecast_type:            hindcast
    Conventions:              CF-1.6 C3S-0.1
    project:                  C3S Seasonal Forecast
    ...                       ...
    forecast_reference_time:  1993-03-01T00:00:00Z
    history:                  Sat Aug 31 01:55:53 2024: ncecat /space/hall5/s...
    data_licence:             1) GRANT OF LICENCE - The Government of Canada ...
    commit:                    
    creation_date:            2024-07-15T20:08:44Z
    NCO:                      netCDF Operators version 5.0.5 (Homepage = http...

In [10]:
test.reftime.values,test.reftime.long_name,test.reftime.units

(array(0.), 'Start date of the forecast', 'hours since 1993-03-01T00:00:00')

In [11]:
test.time.values,test.time.long_name,test.time.units

(array([   6.,   12.,   18.,   24.,   30.,   36.,   42.,   48.,   54.,
          60.,   66.,   72.,   78.,   84.,   90.,   96.,  102.,  108.,
         114.,  120.,  126.,  132.,  138.,  144.,  150.,  156.,  162.,
         168.,  174.,  180.,  186.,  192.,  198.,  204.,  210.,  216.,
         222.,  228.,  234.,  240.,  246.,  252.,  258.,  264.,  270.,
         276.,  282.,  288.,  294.,  300.,  306.,  312.,  318.,  324.,
         330.,  336.,  342.,  348.,  354.,  360.,  366.,  372.,  378.,
         384.,  390.,  396.,  402.,  408.,  414.,  420.,  426.,  432.,
         438.,  444.,  450.,  456.,  462.,  468.,  474.,  480.,  486.,
         492.,  498.,  504.,  510.,  516.,  522.,  528.,  534.,  540.,
         546.,  552.,  558.,  564.,  570.,  576.,  582.,  588.,  594.,
         600.,  606.,  612.,  618.,  624.,  630.,  636.,  642.,  648.,
         654.,  660.,  666.,  672.,  678.,  684.,  690.,  696.,  702.,
         708.,  714.,  720.,  726.,  732.,  738.,  744.,  750.,  756.,
      

In [13]:

test.hcrs.values

array([b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' ',
       b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' ', b' '], dtype='|S1')

In [15]:
test.leadtime.values/24

array([  0.25,   0.5 ,   0.75,   1.  ,   1.25,   1.5 ,   1.75,   2.  ,
         2.25,   2.5 ,   2.75,   3.  ,   3.25,   3.5 ,   3.75,   4.  ,
         4.25,   4.5 ,   4.75,   5.  ,   5.25,   5.5 ,   5.75,   6.  ,
         6.25,   6.5 ,   6.75,   7.  ,   7.25,   7.5 ,   7.75,   8.  ,
         8.25,   8.5 ,   8.75,   9.  ,   9.25,   9.5 ,   9.75,  10.  ,
        10.25,  10.5 ,  10.75,  11.  ,  11.25,  11.5 ,  11.75,  12.  ,
        12.25,  12.5 ,  12.75,  13.  ,  13.25,  13.5 ,  13.75,  14.  ,
        14.25,  14.5 ,  14.75,  15.  ,  15.25,  15.5 ,  15.75,  16.  ,
        16.25,  16.5 ,  16.75,  17.  ,  17.25,  17.5 ,  17.75,  18.  ,
        18.25,  18.5 ,  18.75,  19.  ,  19.25,  19.5 ,  19.75,  20.  ,
        20.25,  20.5 ,  20.75,  21.  ,  21.25,  21.5 ,  21.75,  22.  ,
        22.25,  22.5 ,  22.75,  23.  ,  23.25,  23.5 ,  23.75,  24.  ,
        24.25,  24.5 ,  24.75,  25.  ,  25.25,  25.5 ,  25.75,  26.  ,
        26.25,  26.5 ,  26.75,  27.  ,  27.25,  27.5 ,  27.75,  28.  ,
      

In [19]:
test2=xr.open_dataset('/space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/cwao_CanESM5.1p1bc-v20240611_hindcast_S1995070100_ocean_6hr_surface_tso_r02i00p00.nc',
                     decode_times=False)

In [20]:
test2

<xarray.Dataset> Size: 446MB
Dimensions:      (lat: 180, bnds: 2, leadtime: 860, lon: 360)
Coordinates:
  * lat          (lat) float64 1kB -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * leadtime     (leadtime) float64 7kB 6.0 12.0 18.0 ... 5.154e+03 5.16e+03
  * lon          (lon) float64 3kB 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
    realization  |S31 31B ...
    reftime      float64 8B ...
    time         (leadtime) float64 7kB ...
Dimensions without coordinates: bnds
Data variables:
    hcrs         |S1 1B ...
    lat_bnds     (lat, bnds) float64 3kB ...
    lon_bnds     (lon, bnds) float64 6kB ...
    tso          (leadtime, lat, lon) float64 446MB ...
Attributes: (12/20)
    comment:                  Produced by ECCC (Environment and Climate Chang...
    summary:                  Seasonal Forecast data produced by ECCC as its ...
    title:                    ECCC seasonal forecast model output prepared fo...
    forecast_type:            hindcast
    Conventions:              CF-1.6 C3S-0.1
    project:                  C3S Seasonal Forecast
    ...                       ...
    frequency:                6hr
    forecast_reference_time:  1995-07-01T00:00:00Z
    history:                   
    data_licence:             1) GRANT OF LICENCE - The Government of Canada ...
    commit:                    
    creation_date:            2024-06-19T07:07:00Z

In [41]:
test2.time

<xarray.DataArray 'time' (leadtime: 860)> Size: 7kB
array([   6.,   12.,   18., ..., 5148., 5154., 5160.])
Coordinates:
  * leadtime     (leadtime) float64 7kB 6.0 12.0 18.0 ... 5.154e+03 5.16e+03
    realization  |S31 31B ...
    reftime      float64 8B 0.0
    time         (leadtime) float64 7kB 6.0 12.0 18.0 ... 5.154e+03 5.16e+03
Attributes:
    long_name:      Verification time of the forecast
    units:          hours since 1995-07-01T00:00:00
    calendar:       gregorian
    standard_name:  time

In [40]:
test2.reftime

<xarray.DataArray 'reftime' ()> Size: 8B
array(0.)
Coordinates:
    realization  |S31 31B ...
    reftime      float64 8B 0.0
Attributes:
    standard_name:  forecast_reference_time
    long_name:      Start date of the forecast
    calendar:       gregorian
    units:          hours since 1995-07-01T00:00:00

In [35]:
dt.datetime(1995,7,1)+dt.timedelta(hours=test2.reftime.values)

TypeError: unsupported type for timedelta hours component: numpy.ndarray

In [30]:
test2.time.values

array([   6.,   12.,   18.,   24.,   30.,   36.,   42.,   48.,   54.,
         60.,   66.,   72.,   78.,   84.,   90.,   96.,  102.,  108.,
        114.,  120.,  126.,  132.,  138.,  144.,  150.,  156.,  162.,
        168.,  174.,  180.,  186.,  192.,  198.,  204.,  210.,  216.,
        222.,  228.,  234.,  240.,  246.,  252.,  258.,  264.,  270.,
        276.,  282.,  288.,  294.,  300.,  306.,  312.,  318.,  324.,
        330.,  336.,  342.,  348.,  354.,  360.,  366.,  372.,  378.,
        384.,  390.,  396.,  402.,  408.,  414.,  420.,  426.,  432.,
        438.,  444.,  450.,  456.,  462.,  468.,  474.,  480.,  486.,
        492.,  498.,  504.,  510.,  516.,  522.,  528.,  534.,  540.,
        546.,  552.,  558.,  564.,  570.,  576.,  582.,  588.,  594.,
        600.,  606.,  612.,  618.,  624.,  630.,  636.,  642.,  648.,
        654.,  660.,  666.,  672.,  678.,  684.,  690.,  696.,  702.,
        708.,  714.,  720.,  726.,  732.,  738.,  744.,  750.,  756.,
        762.,  768.,

In [25]:
test3=xr.open_dataset('/space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/testdaily.nc',decode_times=False)

In [26]:
test3

<xarray.Dataset> Size: 111MB
Dimensions:      (lat: 180, bnds: 2, leadtime: 215, lon: 360)
Coordinates:
  * lat          (lat) float64 1kB -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * leadtime     (leadtime) float64 2kB 15.0 39.0 63.0 ... 5.127e+03 5.151e+03
  * lon          (lon) float64 3kB 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
    realization  |S31 31B ...
    reftime      float64 8B ...
    time         (leadtime) float64 2kB ...
Dimensions without coordinates: bnds
Data variables:
    hcrs         |S1 1B ...
    lat_bnds     (lat, bnds) float64 3kB ...
    lon_bnds     (lon, bnds) float64 6kB ...
    tso          (leadtime, lat, lon) float64 111MB ...
Attributes: (12/21)
    comment:                  Produced by ECCC (Environment and Climate Chang...
    summary:                  Seasonal Forecast data produced by ECCC as its ...
    title:                    ECCC seasonal forecast model output prepared fo...
    forecast_type:            hindcast
    Conventions:              CF-1.6 C3S-0.1
    project:                  C3S Seasonal Forecast
    ...                       ...
    forecast_reference_time:  1995-07-01T00:00:00Z
    history:                  Sat Aug 31 02:53:37 2024: ncra --mro -d leadtim...
    data_licence:             1) GRANT OF LICENCE - The Government of Canada ...
    commit:                    
    creation_date:            2024-06-19T06:58:32Z
    NCO:                      netCDF Operators version 5.0.5 (Homepage = http...

In [43]:
test3

<xarray.Dataset> Size: 111MB
Dimensions:      (lat: 180, bnds: 2, leadtime: 215, lon: 360)
Coordinates:
  * lat          (lat) float64 1kB -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * leadtime     (leadtime) float64 2kB 15.0 39.0 63.0 ... 5.127e+03 5.151e+03
  * lon          (lon) float64 3kB 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
    realization  |S31 31B ...
    reftime      float64 8B ...
    time         (leadtime) float64 2kB ...
Dimensions without coordinates: bnds
Data variables:
    hcrs         |S1 1B ...
    lat_bnds     (lat, bnds) float64 3kB ...
    lon_bnds     (lon, bnds) float64 6kB ...
    tso          (leadtime, lat, lon) float64 111MB ...
Attributes: (12/21)
    comment:                  Produced by ECCC (Environment and Climate Chang...
    summary:                  Seasonal Forecast data produced by ECCC as its ...
    title:                    ECCC seasonal forecast model output prepared fo...
    forecast_type:            hindcast
    Conventions:              CF-1.6 C3S-0.1
    project:                  C3S Seasonal Forecast
    ...                       ...
    forecast_reference_time:  1995-07-01T00:00:00Z
    history:                  Sat Aug 31 02:53:37 2024: ncra --mro -d leadtim...
    data_licence:             1) GRANT OF LICENCE - The Government of Canada ...
    commit:                    
    creation_date:            2024-06-19T06:58:32Z
    NCO:                      netCDF Operators version 5.0.5 (Homepage = http...

In [42]:
test3.leadtime

<xarray.DataArray 'leadtime' (leadtime: 215)> Size: 2kB
array([  15.,   39.,   63., ..., 5103., 5127., 5151.])
Coordinates:
  * leadtime     (leadtime) float64 2kB 15.0 39.0 63.0 ... 5.127e+03 5.151e+03
    realization  |S31 31B ...
    reftime      float64 8B ...
    time         (leadtime) float64 2kB ...
Attributes:
    units:          hours
    long_name:      Time elapsed since the start of the forecast
    standard_name:  forecast_period
    cell_methods:   leadtime: mean

In [49]:
np.mean(test2.tso[0:4,100,120].values)

303.6290283203125

In [51]:
test3.tso[0,100,120].values

array(303.61477661)

In [52]:
np.mean(test2.tso[4:8,100,120].values)

303.6485366821289

In [56]:
test3.tso[1,100,120].values

array(303.49358368)

In [60]:
test2b=test2.coarsen({'leadtime':4}).mean()

In [63]:
test2b.tso[0,100,120].values

array(303.62902832)

In [64]:
for yyyy in range(1993,2025):
    for mm in range(1,13):
        if yyyy==2024 and mm>6:
            break
        print(yyyy,mm)

1993 1
1993 2
1993 3
1993 4
1993 5
1993 6
1993 7
1993 8
1993 9
1993 10
1993 11
1993 12
1994 1
1994 2
1994 3
1994 4
1994 5
1994 6
1994 7
1994 8
1994 9
1994 10
1994 11
1994 12
1995 1
1995 2
1995 3
1995 4
1995 5
1995 6
1995 7
1995 8
1995 9
1995 10
1995 11
1995 12
1996 1
1996 2
1996 3
1996 4
1996 5
1996 6
1996 7
1996 8
1996 9
1996 10
1996 11
1996 12
1997 1
1997 2
1997 3
1997 4
1997 5
1997 6
1997 7
1997 8
1997 9
1997 10
1997 11
1997 12
1998 1
1998 2
1998 3
1998 4
1998 5
1998 6
1998 7
1998 8
1998 9
1998 10
1998 11
1998 12
1999 1
1999 2
1999 3
1999 4
1999 5
1999 6
1999 7
1999 8
1999 9
1999 10
1999 11
1999 12
2000 1
2000 2
2000 3
2000 4
2000 5
2000 6
2000 7
2000 8
2000 9
2000 10
2000 11
2000 12
2001 1
2001 2
2001 3
2001 4
2001 5
2001 6
2001 7
2001 8
2001 9
2001 10
2001 11
2001 12
2002 1
2002 2
2002 3
2002 4
2002 5
2002 6
2002 7
2002 8
2002 9
2002 10
2002 11
2002 12
2003 1
2003 2
2003 3
2003 4
2003 5
2003 6
2003 7
2003 8
2003 9
2003 10
2003 11
2003 12
2004 1
2004 2
2004 3
2004 4
2004 5
2004 6
2

In [67]:
import os, sys
import subprocess
import datetime as dt

# run with single argument: number of processors requested (maxproc)

def checkFiles(filelist):
    for ifile in filelist:
        if not os.path.isfile(ifile):
            return False # a file is missing
    return True # no files are missing
    
years = [1993, 2024]
dd=1
hh=0
mdir='/space/hall5/sitestore/eccc/crd/ccrn/users/reo000/data/predictions/cansipsv3_daily/CanESM5'
fnameCanESM=lambda mdir, yyyy, mm, dd, hh, rr:f"{mdir}/cwao_CanESM5.1p1bc-v20240611_hindcast_S{yyyy:04}{mm:02}{dd:02}{hh:02}_ocean_6hr_surface_tso_r{rr:02}i00p00.nc"
fnameCanESMjoined=lambda mdir, yyyy, mm, dd, hh:f"{mdir}/joined/cwao_CanESM5.1p1bc-v20240611_hindcast_S{yyyy:04}{mm:02}{dd:02}{hh:02}_ocean_6hr_surface_tso.nc"
cmdlist=[]
for yyyy in range(years[0],years[1]+1):
    for mm in range(1,13):
        if yyyy==2024 and mm>6:
            break
        flist=[fnameCanESM(mdir,yyyy,mm,dd,hh,ii) for ii in range(1,21)]
        try:
            assert checkFiles(flist) # make sure files exist
        except:
            print(flist)
            raise